rusticl: Get bindgen to skip functions with variadic macros
On aarch64, compilation would fail with:

error: `extern` block uses type `[u64; 4]`, which is not FFI-safe
    --> src/gallium/frontends/rusticl/rusticl_mesa_bindings.rs:1027:15
     |
1027 |         args: va_list,
     |               ^^^^^^^ not FFI-safe
     |
     = note: `-D improper-ctypes` implied by `-D warnings`
     = help: consider passing a pointer to the array
     = note: passing raw arrays by value is not FFI-safe

This doesn't happen on at least x86_64 because that argument would be a
pointer, thus avoiding the FFI safety concern:

args: *mut va_list,

Signed-off-by: Tomeu Vizoso <tomeu.vizoso@collabora.com>
Reviewed-by: Faith Ekstrand <faith.ekstrand@collabora.com>